-- MySQL Script generated by MySQL Workbench
-- Mon Jun 17 14:06:14 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema clinica_db_lohanny
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema clinica_db_lohanny
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `clinica_db_lohanny` DEFAULT CHARACTER SET utf8 ;
USE `clinica_db_lohanny` ;

-- -----------------------------------------------------
-- Table `clinica_db_lohanny`.`convenios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `clinica_db_lohanny`.`convenios` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(90) NOT NULL,
  `cnpj` VARCHAR(18) NOT NULL,
  `tempo_carencia` INT(3) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `clinica_db_lohanny`.`pacientes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `clinica_db_lohanny`.`pacientes` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(90) NOT NULL,
  `data_nascimento` DATE NOT NULL,
  `endereco` VARCHAR(250) NOT NULL,
  `telefone` VARCHAR(15) NOT NULL,
  `email` VARCHAR(120) NOT NULL,
  `cpf` VARCHAR(14) NOT NULL,
  `rg` VARCHAR(13) NOT NULL,
  `convenio_id` INT NULL,
  `carteira_convenio` VARCHAR(25) NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_convenio_pacientes_idx` (`convenio_id` ASC) VISIBLE,
  CONSTRAINT `fk_convenio_pacientes`
    FOREIGN KEY (`convenio_id`)
    REFERENCES `clinica_db_lohanny`.`convenios` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `clinica_db_lohanny`.`medicos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `clinica_db_lohanny`.`medicos` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(90) NOT NULL,
  `data_nascimento` DATE NOT NULL,
  `cpf` VARCHAR(14) NOT NULL,
  `crm` VARCHAR(25) NOT NULL,
  `uf_crm` VARCHAR(2) NOT NULL,
  `telefone` VARCHAR(15) NOT NULL,
  `endereco` VARCHAR(250) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `clinica_db_lohanny`.`especialidades`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `clinica_db_lohanny`.`especialidades` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(90) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `clinica_db_lohanny`.`especialidades_medicos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `clinica_db_lohanny`.`especialidades_medicos` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `medico_id` INT NOT NULL,
  `especialidade_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_especialidade_especmedicos_idx` (`especialidade_id` ASC) VISIBLE,
  INDEX `fk_medico_especmedico_idx` (`medico_id` ASC) VISIBLE,
  CONSTRAINT `fk_especialidade_especmedico`
    FOREIGN KEY (`especialidade_id`)
    REFERENCES `clinica_db_lohanny`.`especialidades` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_medico_especmedico`
    FOREIGN KEY (`medico_id`)
    REFERENCES `clinica_db_lohanny`.`medicos` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `clinica_db_lohanny`.`consultas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `clinica_db_lohanny`.`consultas` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `data_hora` DATETIME NOT NULL,
  `medico_id` INT NOT NULL,
  `paciente_id` INT NOT NULL,
  `valor` DECIMAL(7,2) NOT NULL,
  `especmedico_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_medico_id_idx` (`medico_id` ASC) VISIBLE,
  INDEX `fk_paciente_id_idx` (`paciente_id` ASC) VISIBLE,
  INDEX `fk_especmedico_id_idx` (`especmedico_id` ASC) VISIBLE,
  CONSTRAINT `fk_medico_consultas`
    FOREIGN KEY (`medico_id`)
    REFERENCES `clinica_db_lohanny`.`medicos` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_paciente_consultas`
    FOREIGN KEY (`paciente_id`)
    REFERENCES `clinica_db_lohanny`.`pacientes` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_especmedico_consultas`
    FOREIGN KEY (`especmedico_id`)
    REFERENCES `clinica_db_lohanny`.`especialidades_medicos` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `clinica_db_lohanny`.`receitas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `clinica_db_lohanny`.`receitas` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `prescricao` VARCHAR(500) NOT NULL,
  `consulta_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_consulta_receitas_idx` (`consulta_id` ASC) VISIBLE,
  CONSTRAINT `fk_consulta_receitas`
    FOREIGN KEY (`consulta_id`)
    REFERENCES `clinica_db_lohanny`.`consultas` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `clinica_db_lohanny`.`tipo_quarto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `clinica_db_lohanny`.`tipo_quarto` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `descricao` VARCHAR(500) NOT NULL,
  `valor_diaria` DECIMAL(7,2) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `clinica_db_lohanny`.`quartos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `clinica_db_lohanny`.`quartos` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `numero` VARCHAR(3) NOT NULL,
  `tipo_quarto_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_tipo_quarto_id_idx` (`tipo_quarto_id` ASC) VISIBLE,
  CONSTRAINT `fk_tipo_quartos`
    FOREIGN KEY (`tipo_quarto_id`)
    REFERENCES `clinica_db_lohanny`.`tipo_quarto` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `clinica_db_lohanny`.`internacoes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `clinica_db_lohanny`.`internacoes` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `data_entrada` DATE NOT NULL,
  `data_prev_alta` DATE NOT NULL,
  `data_alta` DATE NULL,
  `procedimento` VARCHAR(500) NOT NULL,
  `paciente_id` INT NOT NULL,
  `medico_id` INT NOT NULL,
  `quarto_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_internacoes_pacientes1_idx` (`paciente_id` ASC) VISIBLE,
  INDEX `fk_internacoes_medicos1_idx` (`medico_id` ASC) VISIBLE,
  INDEX `fk_quarto_internacoes_idx` (`quarto_id` ASC) VISIBLE,
  CONSTRAINT `fk_pacientes_internacoes`
    FOREIGN KEY (`paciente_id`)
    REFERENCES `clinica_db_lohanny`.`pacientes` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_medicos_internacoes`
    FOREIGN KEY (`medico_id`)
    REFERENCES `clinica_db_lohanny`.`medicos` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_quarto_internacoes`
    FOREIGN KEY (`quarto_id`)
    REFERENCES `clinica_db_lohanny`.`quartos` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `clinica_db_lohanny`.`enfermeiros`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `clinica_db_lohanny`.`enfermeiros` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(90) NOT NULL,
  `cpf` VARCHAR(14) NOT NULL,
  `cre` VARCHAR(25) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `clinica_db_lohanny`.`enfermeiros_internacoes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `clinica_db_lohanny`.`enfermeiros_internacoes` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `enfermeiro_id` INT NOT NULL,
  `internacao_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `enfermeiro_enferinternacoes_idx` (`enfermeiro_id` ASC) VISIBLE,
  INDEX `fk_internacoes_enferinternacoes_idx` (`internacao_id` ASC) VISIBLE,
  CONSTRAINT `fk_enfermeiro_enferinternacoes`
    FOREIGN KEY (`enfermeiro_id`)
    REFERENCES `clinica_db_lohanny`.`enfermeiros` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_internacoes_enferinternacoes`
    FOREIGN KEY (`internacao_id`)
    REFERENCES `clinica_db_lohanny`.`internacoes` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
